## NumPy  - Biblioteca matemática, mais utilizada com Álgebra Linear, vetores e Matrizes

In [2]:
#Importação do NumPy

import numpy as np

Estruturas Unidimensionais

In [5]:
a1 = np.array(['Spark','Hadoop','Python','R'])

In [4]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

## Arrays podem ter listas de tipos diferentes

In [6]:
a2 = np.array([['Altura','Largura','Profundidado'],[42,78,10]]) #passando 2 listas dentro de 1 única lista

In [8]:
a2

array([['Altura', 'Largura', 'Profundidado'],
       ['42', '78', '10']], dtype='<U12')

In [3]:
a3 = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [7]:
a3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
#Tamanho do array

print(a1.shape)
print(a2.shape)
print(a3.shape)

(4,)
(2, 3)
(3, 3)


In [19]:
#Dimensoes do array

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
2


Ausência ou presença de parênteses

Podemos fazer uma analogia com características e ações. O uso do parênteses reflete uma ação, enquanto a ausência reflete uma característica

In [20]:
#O método max() não funciona em arrays do tipo heterogeneo
a3.max()

90

In [21]:
a2.ndim

2

## Método Arange

In [22]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
#Usando start/end - de 0 a 100 de 10 em 10
array = np.arange(0,100,10)
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Criando estruturas de dados com linspace

In [32]:
#Fique atento: A diferença do linspace para o arange é que no arange o último argumento é o incremento
#e no linspace o último argumento ;e o número de elementos do vetor (aleatório)

matriz = np.linspace(0,10,20) #Argumentos: limite inferior, limite superior, numero de elementos
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [31]:
matriz = np.linspace(0,10,5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
matriz = np.linspace(0,5,5)
matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

## Estrutura de Matrizes

In [41]:
#numpy.zeros

matriz = np.zeros((10,10)) #cria uma matriz 10 x 10 de zeros
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
#numpy.ones

matriz = np.ones((10,10)) #cria uma matriz 10 x 10 de uns
matriz

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
#numpy.eye - Produz uma matriz do tipo Identity

matriz = np.eye(10) #cria uma matriz em que a diagonal é comportas de números 1
matriz

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
#numpy.diag - produz o mesmo resultado porrém podemos definir os números da diagonal

matriz = np.diag((2,4,6,8,10,12,14,16,18,20))
matriz

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20]])

In [46]:
#numpy.empty - produz uma matriz vazia

matriz = np.empty((10,5)) 
matriz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## numpy.tile

In [12]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np.tile(np.array([[1,2],[3,4],[5,6]]),3) #multiplica os arrays pelo número do 2o argumento (x3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [51]:
np.tile(np.array([[1,2],[3,4],[5,6]]),(4,6)) #Num de vezes do array na vertical, num de vezes do array na horizontal

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])

In [49]:
np.tile(np.array([[1,2],[3,4],[5,6]]),(3,1)) #Num de vezes do array na vertical, num de vezes do array na horizontal

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])