In [1]:
import numpy as np

In [2]:
#Podemos passar um tipo para o Array por parametro
a = np.array([-10,10,20,30],dtype = 'float')

In [3]:
a

array([-10.,  10.,  20.,  30.])

In [5]:
#A propriedade dtype me retorna o tipo dos elementos do array
a.dtype

dtype('float64')

In [7]:
#Caso eu não passe o tipo para o python, ele definirá automaticamente
b = np.array([-10,10,20,30])
b.dtype

dtype('int32')

In [8]:
#Caso exista um elemento diferente dos demais, o Python irá tipar o array pelo elemento mais específico
c = np.array([10,20,30,40.5])
c.dtype

dtype('float64')

In [9]:
#Podemos ter array de string
d = np.array(['universidade','dos','dados'])
d.dtype

dtype('<U12')

In [10]:
#Array do tipo boleano
e = np.array([False, False, True])
e.dtype

dtype('bool')

## Cast de Arrays

In [11]:
f = np.array([-9,10,20.7])
f.dtype

dtype('float64')

In [12]:
f.astype(int)

array([-9, 10, 20])

## Criando Arrays com operações aritméticas em tempo de execução

In [13]:
#Aprendemos que a função arange serve para criar um array

array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [15]:
#Podemos criar o array com qualquer operação aritmética
array = np.arange(0,10) * 10

In [16]:
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
#Potencia
array = np.arange(0,10) ** 2
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

## Operações Aritméticas entre Arrays

In [19]:
arrayA = np.arange(0,10)
arrayB = np.arange(0,10) + 1

In [20]:
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#Soma
arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
#Subtração
arrayA - arrayB

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [25]:
#Divisão
arrayA / arrayB

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [26]:
#Multiplicação
arrayA * arrayB

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [27]:
#Comparação
arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [28]:
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [29]:
arrayA < arrayB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [30]:
#Podemos ainda utilizar a tabela verdade para comparar dois arrays utilizando por exemplo a logica AND
#True and True = True                True or True = True
#True and False = False              True or False = True
#False and True = False              False or True = True
#False and False = False             False or False = False

array1 = np.array([True,False,True,False])
array2 = np.array([False,False,True,False])
np.logical_and(array1,array2)

array([False, False,  True, False])

In [31]:
np.logical_or(array1,array2)

array([ True, False,  True, False])

## Array com tamanhos diferentes

In [33]:
A = np.array([1,2,3,4,5])
B = np.array([1,2,3])

In [34]:
A + B #nao podemos somar array com tamanhos diferentes

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [35]:
A * B

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

## Dot Product

In [36]:
A = np.array([2,4,6])
B = np.array([2,2,2])

In [37]:
#Hadmard Product - multiplicação indice a indice
A * B

array([ 4,  8, 12])

In [39]:
#Dot Product - pode ser solicitado em provas para cientista de dados
print (np.dot(A,B)) #soma dos produtos (4+8+12)

24


In [40]:
A = np.array([3,7,10])
B = np.array([9,3,2])

In [41]:
#Hadmard Product 
A * B

array([27, 21, 20])

In [42]:
print (np.dot(A,B)) #27+21+20

68


## Cópia de Arrays

In [43]:
A = np.arange(10)

In [44]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
B = A[5:]

In [47]:
B

array([5, 6, 7, 8, 9])

In [48]:
A[:] = 0

In [49]:
B #B altera porque apenas faz referencia ao A. Quando A muda, B muda

array([0, 0, 0, 0, 0])

In [50]:
A = np.arange(10)

In [51]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
B = A[5:].copy() #Com o copy(), B vira de fao uma cópia de A e passa a ser independente

In [53]:
B

array([5, 6, 7, 8, 9])

In [54]:
A[:] = 0

In [55]:
B #B não altera

array([5, 6, 7, 8, 9])