In [1]:
import numpy as np

In [3]:
a = [1,2,11,6,8,18,2]

array = np.array(a)
print(type(array))

<class 'numpy.ndarray'>


In [4]:
array.shape

(7,)

In [5]:
array[0] #Primeiro Elemento

1

In [6]:
array[2] #Elemento índice 2

11

In [7]:
array[-1] #Último elemento

2

In [8]:
array[1:5] #Elementos de 1 a 5 (exclusivo)

array([ 2, 11,  6,  8])

In [9]:
array[1:5:2] #Passo 2

array([2, 6])

In [12]:
print(array[-7:-3]) #De trás para frente

[ 1  2 11  6]


In [14]:
print(array[4:])

[ 8 18  2]


In [15]:
print(array[:4])

[ 1  2 11  6]


In [18]:
print(array[::-1]) #Retorna o array invertido

[ 2 18  8  6 11  2  1]


In [19]:
#Copiando o array por REFERENCIA
b = array[:]

In [20]:
print(b)

[ 1  2 11  6  8 18  2]


In [22]:
#Concatenando 2 arrays

x = np.array([2,6,8,4])
y = np.array([11,8,2])
z = np.concatenate([x,y])

z

array([ 2,  6,  8,  4, 11,  8,  2])