In [1]:
import numpy as np

In [2]:
A = [[1,2,3,4],[5,6,7,8],[10,20,30,40],[50,60,70,80]]
array = np.array(A)

print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [3]:
#Primeira Linha

print(array[0])

[1 2 3 4]


In [4]:
#Linha índice 2

print(array[2])

[10 20 30 40]


In [6]:
#Primrira Linha, Última coluna

print(array[0,-1])

4


In [7]:
#Atribuindo valores a uma posição da matriz

array[0,0] = 0

print(array)

[[ 0  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


## Trabalhando com intervalos

In [10]:
print(array[1:3,1:3])

[[ 6  7]
 [20 30]]


In [14]:
#Trazendo somente a última coluna

print(array[:,-1])

[ 4  8 40 80]


In [15]:
#Trazendo somente a última linha

print(array[-1,:])

[50 60 70 80]


In [16]:
#Concatenando arrays multidimensionais

A = np.array([[1,2],[3,4]])
B = np.array([[5,6]])

In [17]:
C = np.concatenate(A,B)

TypeError: only integer scalar arrays can be converted to a scalar index