In [1]:
#Matrizes são elementos ESTRITAMENTE bidimensionais, o que torna mais fácil as operações aritméticas

In [2]:
import numpy as np

In [3]:
A = np.matrix([[1,2],[3,4]])
B = np.matrix([[5,3],[8,7]])

Z = np.array([
    [[2,6],[8,4]],
    [[2,6],[8,4]],
    [[2,6],[8,4]]
])

Y = np.array([2,6,8,4])

In [4]:
Z = np.matrix([
    [[2,6],[8,4]],
    [[2,6],[8,4]],
    [[2,6],[8,4]]
])

ValueError: matrix must be 2-dimensional

In [6]:
print(type(A))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [7]:
print(type(Z))

<class 'numpy.ndarray'>


In [8]:
print(type(Y))

<class 'numpy.ndarray'>


In [9]:
print(A)

[[1 2]
 [3 4]]


In [10]:
print(Z)

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [11]:
print(Y)

[2 6 8 4]


In [12]:
Z.shape

(3, 2, 2)

In [13]:
Y.shape

(4,)

In [14]:
A.shape

(2, 2)

## Operações

In [16]:
print(A+B)

[[ 6  5]
 [11 11]]


In [17]:
print(B+3)

[[ 8  6]
 [11 10]]


In [18]:
print(A-B)

[[-4 -1]
 [-5 -3]]


In [19]:
A = np.matrix([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [20]:
#Arrumação em índices
print(A*A)

[[ 7 10]
 [15 22]]


In [22]:
#Multiplicando índice a índice
print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


## Inversa

In [24]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [25]:
from numpy.linalg import inv

In [26]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


## Transposta

In [28]:
print(A.T)

[[1 3]
 [2 4]]
