## Transposição e Reshaping de Arrays

In [2]:
import numpy as np

In [3]:
A = np.array([[10,20,30],[40,50,60]])

In [4]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [8]:
np.transpose(A)

array([[10, 40],
       [20, 50],
       [30, 60]])

## Broadcasting

In [10]:
B = np.array([[100,200,300]])

In [11]:
B.T

array([[100],
       [200],
       [300]])

In [12]:
B.T + B

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

## Convertendo Matrizes em Arrays

In [17]:
A = np.array([np.arange(10,60,10),np.arange(100,150,10)])

In [18]:
A

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [19]:
A.shape

(2, 5)

In [21]:
A.ravel() #transforma uma matriz em um array (vetor)

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [22]:
A.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

## Operadores Lógicos

In [24]:
array = np.random.randint(1,10,size=(4,4))

In [25]:
array

array([[1, 9, 5, 6],
       [2, 3, 7, 7],
       [2, 4, 7, 3],
       [8, 9, 4, 4]])

In [26]:
np.any((array % 7) == 0)

True

In [27]:
np.all(array < 11)

True

In [28]:
np.all(array < 9)

False

## Reshaping

In [30]:
array = np.arange(1,16)

In [33]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
array.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Ordenando Arrays

In [36]:
array = np.array([[3,2],[10,-1]])

In [37]:
array

array([[ 3,  2],
       [10, -1]])

In [39]:
#Ordenando por linhas
array.sort(axis=1)

In [40]:
array

array([[ 2,  3],
       [-1, 10]])

In [41]:
array = np.array([[3,2],[10,-1]])

In [42]:
#Ordenando por colunas
array.sort(axis=0)

In [43]:
array

array([[ 3, -1],
       [10,  2]])